### ISSUE TITLE
Test page not rendering in IE 9

### ISSUE THREAD

**Issue by eudaimos** [uiteoi/ico#4]
Tried the test page at: http://reverserisk.com/ico/index.html

I see the text descriptions but the graphs do not render in IE 9 (ok in Chrome).
Here's my About IE
Version: 9.0.8112.16421
Update Versions: 9.0.1

**Comment by uiteoi** [comment]
Thanks for the report. Will try to fix this tomorrow.

**Comment by uiteoi** [comment]
I have tested with the same version 9.0.8112.16421, but with update version 9.0.2 and it works fine.

Can you check again and check if the problem is not due to some configuration parameter?

**Comment by eudaimos** [comment]
I now have 9.0.2 and it's still not working.

Could it be Norton?

**Comment by uiteoi** [comment]
I don't think this could be a firewall issue.

Try this page and tell me if it works:
http://raphaeljs.com/analytics.html

Thanks
