### ISSUE TITLE
IE8: console.log does not exist; transparent color does not work.

### ISSUE THREAD

**Issue by Kirkman** [uiteoi/ico#6]
While testing in IE 8, I came across two problems:
1. The ico.js and ico-min.js files have a console.log() statement, which throws an error in IE8 unless you have developer tools open. And obviously most users won't have the devtools open.
2.  Setting a line's color to be "transparent" works in other browsers, but it doesn't seem to be honored by IE8.

**Comment by uiteoi** [comment]
Thanks for your feedback, we will be fixing these issues shortly.

**Comment by uiteoi** [comment]
1. fixed, please verify
2. Ico does not manage attributes directly, this is therefore either an issue with Raphael or VML under IE8.

I therefore close this issue, please reopen if you think I should do something about it in Ico.

**Comment by Kirkman** [comment]
Issue 1 still persists in IE8 after your fix. Here is the error message:

Message: 'console' is undefined
Line: 24
Char: 10
Code: 0
URI: http://joshrenaud.com/pd/lib/ico/ico.js

**Comment by Kirkman** [comment]
I would like to offer an additional suggestion: Can you make the the debugging output optional? There could be an attribute like "Debug: true".  This would let people choose to turn it off.

**Comment by uiteoi** [comment]
Sorry for the non-working fix, it should work now. Please test again.

You can also provide your own debug function by defining it this way:
function debug( message ) {
}

**Comment by Kirkman** [comment]
I can verify the issue is now fixed.

**Comment by uiteoi** [comment]
Thanks for the verification.
